src/app/Models/Battle.cs
namespace DogsVsCats.Models
{
    public class Battle
    {
        public Fighter Dog { get; set; }

        public Fighter Cat { get; set; }
    }
}

src/app/Models/Fighter.cs
namespace DogsVsCats.Models
{
    public class Fighter
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public string Image { get; set; }

        public int Votes { get; set; }
    }
}

src/app/Models/FighterType.cs
namespace DogsVsCats.Models
{
    public enum FighterType
    {
        Dog,
        Cat
    }
}

src/app/Models/GcpConfiguration.cs
namespace DogsVsCats.Models
{
    public class GcpConfiguration
    {
        public string ProjectId { get; set; }

        public string BucketName { get; set; }

        public string Topic { get; set; }
    }
}

src/app/ViewModels/StatsViewModel.cs
using System.Collections.Generic;
using DogsVsCats.Models;

namespace DogsVsCats.ViewModels
{
    public class StatsViewModel
    {
        public List<Fighter> Fighters { get; set; }
    }
}

src/app/ViewModels/UploadViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace DogsVsCats.ViewModels
{
    public class UploadViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public IFormFile Image { get; set; }

        public string Errors { get; set; }

        public bool IsSuccess { get; set; }
    }
}

src/app/ViewModels/VoteViewModel.cs
namespace DogsVsCats.ViewModels
{
    public class VoteViewModel
    {
        public string DogId { get; set; }

        public string DogName { get; set; }

        public string DogImagePath { get; set; }

        public string CatId { get; set; }

        public string CatName { get; set; }

        public string CatImagePath { get; set; }
    }
}

src/app/Controllers/StatsController.cs
using System.Linq;
using System.Threading.Tasks;
using DogsVsCats.Contracts;
using DogsVsCats.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DogsVsCats.Controllers
{
    public class StatsController : Controller
    {
        private readonly IStatsService _statsService;

        public StatsController(IStatsService statsService)
        {
            _statsService = statsService;
        }

        public async Task<IActionResult> Index()
        {
            var stats = await _statsService.GetStatsAsync();

            return View(new StatsViewModel { Fighters = stats.ToList() });
        }
    }
}

src/app/Controllers/UploadController.cs
using System.Threading.Tasks;
using DogsVsCats.Contracts;
using DogsVsCats.Models;
using DogsVsCats.ViewModels;
using Google.Cloud.PubSub.V1;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace DogsVsCats.Controllers
{
    public class UploadController : Controller
    {
        private readonly IDataService _dataService;
        private readonly IImageAnalyser _imageDescriptor;
        private readonly GcpConfiguration _config;

        private readonly ILogger _logger;

        public UploadController(IDataService dataService, IImageAnalyser imageDescriptor, GcpConfiguration config, ILogger<UploadController> logger)
        {
            _dataService = dataService;
            _imageDescriptor = imageDescriptor;
            _config = config;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(UploadViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Errors = "All fields are required!";
                return View(model);
            }

            var image = model.Image.OpenReadStream();

            var fighterType = await _imageDescriptor.GetFighterTypeAsync(image);

            if (!fighterType.HasValue)
            {
                model.Errors = "Please upload an image of either a dog or a cat";
                return View(model);
            }

            var fighterId = await _dataService.SaveFighterAsync(new Fighter { Name = model.Name },
                            image, model.Image.ContentType, fighterType.Value);

            TopicName topicName = new TopicName(_config.ProjectId, _config.Topic);
            PublisherClient publisher = await PublisherClient.CreateAsync(topicName);
            string messageId = await publisher.PublishAsync(fighterId);

            _logger.LogInformation($"Published message : {messageId}");

            return View(new UploadViewModel { IsSuccess = true });
        }
    }
}

src/app/Controllers/VoteController.cs
using System.Threading.Tasks;
using DogsVsCats.Contracts;
using DogsVsCats.Services;
using DogsVsCats.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DogsVsCats.Controllers
{
    public class VoteController : Controller
    {
        private readonly IDataService _dataService;
        private readonly ILogger _logger;

        public VoteController(IDataService dataStore, ILogger<VoteController> logger)
        {
            _dataService = dataStore;
            _logger = logger;
        }

        public async Task<IActionResult> Index([FromServices]BattleGenerator battleGenerator)
        {
            var battle = await battleGenerator.GenerateBattleAsync();

            if (battle == null)
            {
                _logger.LogWarning("No battle found");

                return View("Empty");
            }

            _logger.LogInformation($"Requesting {battle.Dog.Name} vs {battle.Cat.Name}");

            var model = new VoteViewModel
            {
                DogId = battle.Dog.Id,
                DogName = battle.Dog.Name,
                DogImagePath = battle.Dog.Image,
                CatId = battle.Cat.Id,
                CatName = battle.Cat.Name,
                CatImagePath = battle.Cat.Image
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Vote(string fighterId)
        {
            if (string.IsNullOrEmpty(fighterId))
            {
                _logger.LogTrace("user voted with an empty id");

                return StatusCode(StatusCodes.Status422UnprocessableEntity);
            }

            await _dataService.SetFighterVoteAsync(fighterId);

            return RedirectToAction("Index");
        }

        public IActionResult Error()
        {
            _logger.LogError("Error view sent to the user");
            return View();
        }
    }
}

src/app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vote" asp-action="Index">Vote</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Upload" asp-action="Index">Upload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stats" asp-action="Index">Stats</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/app/Views/Stats/Index.cshtml
@model StatsViewModel
@{
    ViewData["Title"] = "Stats";
}

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th style="width:10%">#</th>
                <th style="width:20%"></th>
                <th style="width:55%">Name</th>
                <th style="width:15%">Votes</th>
            </tr>
        </thead>
        <tbody>
            @for(var i = 0; i < Model.Fighters.Count; i++)
            {
                var fighter = Model.Fighters[i];
                <tr>
                    <th scope="row">@(i+1)</th>
                    <td>
                        <img src="@fighter.Image" class="figure-img img-fluid rounded" alt="@fighter.Name" 
                                asp-append-version="true" width="120" height="120">
                    </td>
                    <td>@fighter.Name</td>
                    <td>@fighter.Votes</td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/app/Views/Upload/Index.cshtml
@model UploadViewModel
@{
    ViewData["Title"] = "Upload";
}

<div class="container mt-5">
    <div class="row">
        <form method="post" enctype="multipart/form-data" asp-controller="Upload" asp-action="Index"  >
            <div class="form-group">
                <label for="Name">Name</label>
                <input asp-for="Name" type="text" class="form-control" required placeholder="pick a name">
            </div>
            <div class="form-group">
                <label for="Image">Image</label>
                <input type="file" class="form-control-file" asp-for="Image">
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>

    @if(Model != null)
    {
        if(!string.IsNullOrEmpty(Model.Errors))
        {
            <div class="row mt-2">
                <div class="alert alert-danger" role="alert">
                    @Model.Errors
                </div>
            </div>
        }
        else if(Model.IsSuccess)
        {
            <div class="row mt-2">
                <div class="alert alert-success" role="alert">
                    Upload Successful
                </div>
            </div>
        }
    }
</div>

src/app/Views/Vote/Empty.cshtml
@{
    ViewData["Title"] = "Votes";
}

<div class="container mt-5">
    <p class="text-center">Please upload some pictures first :)</p>
</div>

src/app/Views/Vote/Index.cshtml
@model VoteViewModel
@{
    ViewData["Title"] = "Votes";
}

<div class="container mt-5">
    <form id="voteForm" asp-controller="Vote" asp-action="Vote" method="POST">
        <div class="row justify-content-md-center align-items-center">
            <div class="col-sm-5 col-md-4 col-lg-3">
                <div class="fighter" onclick="submitForm('@Model.DogId')">
                    <figure class="figure">
                        <img src="@Model.DogImagePath" class="figure-img img-fluid rounded" alt="@Model.DogName" 
                            asp-append-version="true" width="250" height="250">
                        <figcaption class="figure-caption text-right">@Model.DogName</figcaption>
                    </figure>
                </div>
            </div>
            <div class="col-1 col-sm-1">
                <h6 class="text-center">VS</h6>
            </div>
            <div class="col-sm-5 col-md-4 col-lg-3 fighter">
                <div class="fighter" onclick="submitForm('@Model.CatId')">
                    <figure class="figure">
                            <img src="@Model.CatImagePath" class="figure-img img-fluid rounded" alt="@Model.CatName" 
                                asp-append-version="true" width="250" height="250">
                            <figcaption class="figure-caption text-right">@Model.CatName</figcaption>
                    </figure>
                </div>
            </div>
        </div>
        <input type="hidden" name="fighterId"/>
    </form>
</div>

<script>
    function submitForm(fighterId) {
        document.getElementsByName("fighterId")[0].value = fighterId;
        document.getElementById("voteForm").submit();
    }
</script>